### ISSUE TITLE
New symbol: Strike-slip fault, planetary (fgdc 25.013)

### ISSUE THREAD

**Issue by afrigeri** [afrigeri/geologic-symbols-qgis#1]
Find attached the symbol - it's not using svg symbol, to be tested.

[fgdc-25.013.xml.txt](https://github.com/afrigeri/geologic-symbols-qgis/files/3336186/fgdc-25.013.xml.txt)

**Comment by valemercurii** [comment]
Find attached strike-slip faults, planetary. Symbols 25.013 to 25.020.

[fgdc-25.013-020_VG20190628.xml.txt](https://github.com/afrigeri/geologic-symbols-qgis/files/3339721/fgdc-25.013-020_VG20190628.xml.txt)

**Comment by afrigeri** [comment]
Nice!  Makes use of the __Hash Line symbol type__ introduced in the latest 3.8.x-Zanzibar release.  Changing the minimum QGIS version requirement makes sense.

Please send one single xml symbol/svg graphic per issue (in this case fgdc 25.013), so we can add to the src/xml src/svg directory and build the updated library.

**Comment by afrigeri** [comment]
Added the 7 strike-slip symbols: [cbd3a43](https://github.com/afrigeri/geologic-symbols-qgis/commit/cbd3a4331de66e143232f682d221391ade5cfe8f#diff-4ac32a78649ca5bdd8e0ba38b7006a1e)
