### ISSUE TITLE
some issues with symbols

### ISSUE THREAD

**Issue by luca-penasa** [afrigeri/geologic-symbols-qgis#10]
I've been adding in my fork some consistency checking for the symbols, feel free to merge with the codebase if you want (or I can provide a pull request). Here is a list the detected problems:

18:27:22,323 root ERROR filename 25.009: Cannot split name, missing ":" ? in @fgdc-25.9@1. check naming inside xml
18:27:22,325 root WARNING filename 25.098: description contains newline char.
18:27:22,337 root ERROR filename 25.117: Cannot split name, missing ":" ? in @fgdc-25.117@0. check naming inside xml
18:27:22,337 root WARNING filename 25.117: xml referencing to missing svg at svg/symbols/fgdc/fgdc-25.117_arrow.svg, expected at full path /run/media/luca/data/Code/geologic-symbols-qgis.git/src/svg/svg/symbols/fgdc/fgdc-25.117_arrow.svg
18:27:22,349 root WARNING filename 25.081: description contains newline char.
18:27:22,354 root WARNING filename 25.077: description contains newline char.
18:27:22,360 root WARNING filename 25.076: description contains newline char.
18:27:22,379 root WARNING filename 25.080: description contains newline char.
18:27:22,393 root WARNING filename 25.126: description contains newline char.
18:27:22,393 root WARNING filename 25.126: xml referencing to missing svg at symbols/fgdc/fgdc-25.117_arrow.svg, expected at full path /run/media/luca/data/Code/geologic-symbols-qgis.git/src/svg/symbols/fgdc/fgdc-25.117_arrow.svg
18:27:22,396 root ERROR filename 25.074: Cannot split name, missing ":" ? in @fgdc-25.074@0. check naming inside xml
18:27:22,398 root WARNING filename 25.078: description contains newline char.
18:27:22,402 root ERROR filename 25.118: Cannot split name, missing ":" ? in @fgdc-25.118@0. check naming inside xml
18:27:22,408 root ERROR filename 25.084: Cannot split name, missing ":" ? in @fgdc-25.84@1. check naming inside xml
18:27:22,411 root ERROR filename 25.012: Cannot split name, missing ":" ? in @fgdc-25.12@1. check naming inside xml
18:27:22,417 root WARNING filename 25.094: description contains newline char.
18:27:22,421 root ERROR filename 25.010: Cannot split name, missing ":" ? in @fgdc-25.10@1. check naming inside xml
18:27:22,423 root WARNING filename 25.124: description contains newline char.
18:27:22,441 root WARNING filename 25.085: description contains newline char.
18:27:22,450 root ERROR filename 25.024: filename 25.024 and code 25.034 mismatch
18:27:22,453 root ERROR filename 25.011: Cannot split name, missing ":" ? in @fgdc-25.11@1. check naming inside xml
18:27:22,462 root ERROR filename 25.119: Cannot split name, missing ":" ? in @fgdc-25.119@0. check naming inside xml
18:27:22,466 root WARNING filename 25.082: description contains newline char.

Most notably:
- a filename / xml name mismatch "filename 25.024: filename 25.024 and code 25.034 mismatch"
- some svg (for symbols using svgs) are pointing to the wrong path for the svg they need: those are 25.117,  25.126. This might be (part of) the problem of some thumbnails in the status table. i.e.
![image](https://user-images.githubusercontent.com/2051141/64632646-c069fe00-d3f9-11e9-809b-f8643f17effb.png)
where the missing svgs are substituted with "?".

Furthermore I suspect that when generating the pngs one should pass the full path for the svg maybe to fully solve the problem.
luca

**Comment by afrigeri** [comment]
@luca-penasa, thanks for the name parsing control code, please go ahead with the pull request.

For the png rendering (last point), it was an issue with the SVG path at the moment of rendering - now it's fixed and the SVG patterns and symbols are rendered in the table.
