### ISSUE TITLE
ARPA prova

### ISSUE THREAD

**Issue by GISsymbology** [afrigeri/geologic-symbols-qgis#14]
ARPA, MZS

[MZS_001:prova.xml.zip](https://github.com/afrigeri/geologic-symbols-qgis/files/4237260/MZS_001.prova.xml.zip)

**Comment by afrigeri** [comment]
Hi Luca,

for the symbol to be added we need:

1 - the name for the authority part, which normally is the acronym of the geologic service / society / group proposing the symbol.  We currently have symbols from the Federal Geographic Data Committee, which works on standards used in the US.

2 - an ID for the symbol, which identifies the symbol in the catalog/manual.

3 - a description of the symbol.  For regional agencies, local languages are ok.

For this symbol an example of _name_ (see the xml file) would be:  

`001: Conoide alluvionale`

for the __arpa-piemonte__ auth (which will appear in the tag field of the style manager).

Just confirm and we go on including the symbol.

**Comment by GISsymbology** [comment]
It's ok for this one. I can also use the traditional pull request method to commit new/modified symbols ?

**Comment by afrigeri** [comment]
Sure.

**Comment by GISsymbology** [comment]
I try to use the script to symbolsplitter.py to split my symbology but I've this error [0].

[faglie.xml.zip](https://github.com/afrigeri/geologic-symbols-qgis/files/4247116/faglie.xml.zip)


[0]
Traceback (most recent call last):
  File "splitter.py", line 17, in <module>
    for event, elem in context:
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1221, in iterator
    yield from pullparser.read_events()
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1296, in read_events
    raise event
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1268, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 53, column 68

**Comment by afrigeri** [comment]
Luca,

the faglie.xml.zip file contains it's an HTML page, with listed the actual qgis_style xml file (it's a github html page - unzip the file, rename it with .html extension and open it with a web browser).

Please try on the actual xml file and see if symbolsplitter.py works.

Alessandro

**Comment by afrigeri** [comment]
inactive. closing.
