### ISSUE TITLE
New symbols: Thrust fault, planetary (fgdc 25.021, 25.022, 25.023, 25.024)

### ISSUE THREAD

**Issue by valemercurii** [afrigeri/geologic-symbols-qgis#2]
Planetary thrust fault fgdc symbols from 25.021 to 25.024 do not specify the distance between sawteeth. It turns out to be  12.75 mm (see dash distance in 25.022, fgdc manual).

[fgdc_25.021-024_VG20190628.xml.txt](https://github.com/afrigeri/geologic-symbols-qgis/files/3339836/fgdc_25.021-024_VG20190628.xml.txt)

**Comment by afrigeri** [comment]
Good point.  please add one symbol per xml file, so we can add them to the src/xml dir.

**Comment by afrigeri** [comment]
Added the single xmls to the src dir. Good job! 96cd7481d313e5fd70eeeb88d64f3d122651172f
