### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by valemercurii** [afrigeri/geologic-symbols-qgis#3]
2019-06-28 | Bundle update of line symbols:

- Added symbols from 25.013 to 25.32;
- Restyling of 25.058: Narrow channel, planetary;
- Update of 100% black symbols;
- Update of "fgdc 100% purple" symbols;
- Update of "fgdc 100% violet" symbols;
- Update of "fgdc 100% brown" symbols.

[fgdc_update_VG20190628.xml.txt](https://github.com/afrigeri/geologic-symbols-qgis/files/3339863/fgdc_update_VG20190628.xml.txt)

**Comment by afrigeri** [comment]
New symbols should be submitted as single xml files, so we can add them to the xml directory to create the updated library.
