### ISSUE TITLE
Missing Strike-Slip SVG

### ISSUE THREAD

**Issue by mahunter14** [afrigeri/geologic-symbols-qgis#5]
The SVG directory only contains the arrow graphic.

**Comment by mahunter14** [comment]
I see they are in geologic-symbols repo - should I be working on that one or are they being maintained separately?

**Comment by afrigeri** [comment]
Hi @mahunterUSGS! the strike-slip symbols in the latest [qgis symbols library](https://github.com/afrigeri/geologic-symbols-qgis/raw/master/dist/geologic_symbols_qgis.zip) now use the brand new QGIS 3.8, which introduced the support of [Hashed Line symbol type](https://north-road.com/2019/04/05/qgis-and-slyr-now-with-hash-lines-support/), see [system requirements](https://github.com/afrigeri/geologic-symbols-qgis#system-requirements  ).  This maximizes the symbol design within the XML,  minimizing the use of separated SVG symbols.

The [geologic-symbols](https://github.com/afrigeri/geologic-symbols) repo was started by @anass and me with the initial idea of a more broad project to develop a unified cross-software platform library - which potentially is the mid-long term goal.   But AFAIK there is still not a common format or language descriptor for GIS symbols (apart from the [Styled Layer Descriptor](https://en.wikipedia.org/wiki/Styled_Layer_Descriptor), which does not seem to be adopted broadly yet).  So, for now, that repo is not active in the sense of developments/building of symbols library. 

This [geologic-symbols-qgis](https://github.com/afrigeri/geologic-symbols-qgis) repo focuses on the building of:

1. an ordered and well documented geologic symbols library which works out of the box with QGIS (version >= 3.8), and  
2. an environment where to contribute incrementally with new symbols (e.g. coming from different geologic survey institutions or particular conventions).  

Until now the QGIS library contains about 40 geologic symbols coming from FGDC, but more from FGDC or another geologic survey can be added as well or existing ones can be improved/fixed (see [contributing instructions](https://github.com/afrigeri/geologic-symbols-qgis#how-to-contribute-add-new-symbols-or-fix-existing-ones) )

**Comment by mahunter14** [comment]
That makes sense, thank you for the clarification. I agree the ultimate goal should be full cross-platform interoperability, but building the catalog for Q is the best way to start.
