### ISSUE TITLE
31 New symbols! 

### ISSUE THREAD

**Issue by ericaluzzi** [afrigeri/geologic-symbols-qgis#8]
-25.053
-25.054
-25.075
-25.076
-25.077
-25.078
-25.079
-25.080
-25.081
-25.082
-25.085
-25.087
-25.088
-25.089
-25.091
-25.092
-25.093
-25.094
-25.095
-25.097
-25.098
-25.099
-25.100
-25.105
-25.106
-25.107
-25.109
-25.111
-25.114
-25.115
-25.116

[new-symbols.zip](https://github.com/afrigeri/geologic-symbols-qgis/files/3595265/new-symbols.zip)

(I made a zip containing the single xml files because the .xml cannot be uploaded on github)

**Comment by afrigeri** [comment]
That's a massive contribution, great job @ericaluzzi!  

symbols have been [added to the repository](https://github.com/afrigeri/geologic-symbols-qgis/commit/d45e43525af539517b3b541f6496d51152366aa5) and are available in the distributed zipfile.
